name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 55 15 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 准备完成
      uses: actions/checkout@main

    - name: 下载架构编译配置文件
      run: |
        mkdir -p ./rk35xx
        rm -f ./rk35xx/.config
        wget -O ./rk35xx/feeds.conf https://fw0.koolcenter.com/iStoreOS/station-p2/feeds.conf --no-check-certificate
        wget -O ./rk35xx/.config https://fw0.koolcenter.com/iStoreOS/station-p2/config.buildinfo --no-check-certificate

    - name: 注释软件源
      run: |
        #注释应用过滤
        sed -i 's/^.*OpenAppFilter.*/#&/' feeds.conf
        
        #移除应用过滤
        sed -i 's/CONFIG_PACKAGE_appfilter=y/CONFIG_PACKAGE_appfilter=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-oaf=y/CONFIG_PACKAGE_kmod-oaf=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-app-oaf=y/CONFIG_PACKAGE_luci-app-oaf=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-oaf-zh-cn=y/CONFIG_PACKAGE_luci-i18n-oaf-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-oaf=y/CONFIG_PACKAGE_kmod-oaf=n/' .config
        
        #移除网络唤醒
        sed -i 's/CONFIG_PACKAGE_luci-app-wol=y/CONFIG_PACKAGE_luci-app-wol=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y/CONFIG_PACKAGE_luci-i18n-wol-zh-cn=n/' .config
        
        #移除硬盘休眠
        sed -i 's/CONFIG_PACKAGE_luci-app-hd-idle=y/CONFIG_PACKAGE_luci-app-hd-idle=n/' .config
        sed -i 's/CONFIG_PACKAGE_hd-idle=y/CONFIG_PACKAGE_hd-idle=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y/CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=n/' .config
        
        #移除samba4
        sed -i 's/CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=y/CONFIG_PACKAGE_luci-i18n-samba4-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-app-samba4=y/CONFIG_PACKAGE_luci-app-samba4=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_AVAHI=y/CONFIG_SAMBA4_SERVER_AVAHI=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_NETBIOS=y/CONFIG_SAMBA4_SERVER_NETBIOS=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_VFS=y/CONFIG_SAMBA4_SERVER_VFS=n/' .config
        sed -i 's/CONFIG_SAMBA4_SERVER_WSDD2=y/CONFIG_SAMBA4_SERVER_WSDD2=n/' .config
        sed -i 's/CONFIG_PACKAGE_samba4-libs=y/CONFIG_PACKAGE_samba4-libs=n/' .config
        sed -i 's/CONFIG_PACKAGE_samba4-server=y/CONFIG_PACKAGE_samba4-server=n/' .config
        
        #移除统一文件共享
        sed -i 's/CONFIG_PACKAGE_luci-app-unishare=y/CONFIG_PACKAGE_luci-app-unishare=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-unishare-zh-cn=y/CONFIG_PACKAGE_luci-i18n-unishare-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_unishare=y/CONFIG_PACKAGE_unishare=n/' .config
        
        #移除NFS
        sed -i 's/CONFIG_PACKAGE_luci-app-nfs=y/CONFIG_PACKAGE_luci-app-nfs=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-nfs-zh-cn=y/CONFIG_PACKAGE_luci-i18n-nfs-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-kernel-server=y/CONFIG_PACKAGE_nfs-kernel-server=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-kernel-server-utils=y/CONFIG_PACKAGE_nfs-kernel-server-utils=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-utils=y/CONFIG_PACKAGE_nfs-utils=n/' .config
        sed -i 's/CONFIG_PACKAGE_nfs-utils-libs=y/CONFIG_PACKAGE_nfs-utils-libs=n/' .config
        sed -i 's/CONFIG_NFS_KERNEL_SERVER_V4=y/CONFIG_NFS_KERNEL_SERVER_V4=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs=y/CONFIG_PACKAGE_kmod-fs-nfs=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-common=y/CONFIG_PACKAGE_kmod-fs-nfs-common=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=y/CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-v3=y/CONFIG_PACKAGE_kmod-fs-nfs-v3=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfs-v4=y/CONFIG_PACKAGE_kmod-fs-nfs-v4=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-nfsd=y/CONFIG_PACKAGE_kmod-fs-nfsd=n/' .config
        
        #移除挂载网络共享
        sed -i 's/CONFIG_PACKAGE_luci-app-cifs-mount=y/CONFIG_PACKAGE_luci-app-cifs-mount=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-cifs-mount-zh-cn=y/CONFIG_PACKAGE_luci-i18n-cifs-mount-zh-cn=n/' .config
        sed -i 's/CONFIG_PACKAGE_cifsmount=y/CONFIG_PACKAGE_cifsmount=n/' .config
        sed -i 's/CONFIG_PACKAGE_kmod-fs-cifs=y/CONFIG_PACKAGE_kmod-fs-cifs=n/' .config

        #移除挂载网络共享
        sed -i 's/CONFIG_PACKAGE_luci-app-ota=y/CONFIG_PACKAGE_luci-app-ota=n/' .config
        sed -i 's/CONFIG_PACKAGE_luci-i18n-ota-zh-cn=y/CONFIG_PACKAGE_luci-i18n-ota-zh-cn=n/' .config
        
        # 移除 bootstrap 主题
        sed -i 's/CONFIG_PACKAGE_luci-theme-bootstrap=y/CONFIG_PACKAGE_luci-theme-bootstrap=n/' .config

        # 移除 动态DNS
        sed -i 's/CONFIG_PACKAGE_luci-app-ddns=y/CONFIG_PACKAGE_luci-app-ddns=n/' .config

        FILE_PATH="./rk35xx/.config"
        if [ -f "$FILE_PATH" ] && [ -s "$FILE_PATH" ]; then
           content=$(cat ${GITHUB_WORKSPACE}/configfiles/config_data.txt)
           configdata=$(echo "$content" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
           sed -i "/CONFIG_TARGET_DEVICE_rockchip_.*=.*/d" ./rk35xx/.config
           sed -i "/CONFIG_PACKAGE_dtc.*=.*/d" ./rk35xx/.config
           sed -i "/CONFIG_PACKAGE_luci-app-istorex.*=.*/d" ./rk35xx/.config
           sed -i "/#\s*CONFIG_TARGET_DEVICE_rockchip_rk35xx_DEVICE_jp_tvbox\s*is\s*not\s*set/d" ./rk35xx/.config
           sed -i "/#\s*CONFIG_TARGET_DEVICE_rockchip_rk35xx_DEVICE_panther_x2\s*is\s*not\s*set/d" ./rk35xx/.config
           sed -i "/#\s*CONFIG_TARGET_DEVICE_rockchip_rk35xx_DEVICE_dg_nas\s*is\s*not\s*set/d" ./rk35xx/.config
           echo -e "\\n$configdata" >> ./rk35xx/.config
           # 清除.config配置文件里面重复的配置项
           configdata2=$(cat ./rk35xx/.config)
           echo "$configdata2" | awk '!seen[$0]++' > ./rk35xx/.config
        else
           echo "不处理数据。"
        fi

    - name: 同步配置
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"

    - name: 删除运行记录
      uses: xiaomeng9597/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ secrets.ACCESS_TOKEN }}
